### PR TITLE
Added Support for C++20 submission on Codeforces and added Automatic save before submitting to OJ

### PR DESCRIPTION
**Pull request by AG-7219**

### CODE REVIEW

**Comment by Dipankar-Kumar-Singh** [comment]
I was eagerly waiting for this feature .... @agrawal-d please approve this merge and add this feature.

**Comment by agrawal-d** [comment]
Hi @AG-7219,
Sorry for the delay in getting back to you.
Can you please

1. Remove all changes in `package-lock.json`.
2. Add the bug fix you had included in commit d6b159c28fd8cb5c7d0c9ba4a433db3356ee54ef.

Once you have made the above changes, I'll merge the PR.

Thanks a lot for your contribution!

**Comment by AG-7219** [comment]
Hey @agrawal-d, I accidentally closed the previous PR and removed the changes for the bug fix as was suggested by you in the previous PR but thanks for considering the bug.
Also, i didn't change anything manually in the package.lock.json but the changes might be there because of different node versions, anyways they are reverted back now.
I hope everything is fine now. 🥂

**Comment by agrawal-d** [comment]
Looks good now, thanks @AG-7219! I'll push an update to the store in a few days.

**Pull request merged**
