### PR TITLE
Add option to make a copy of files in a specified folder

### PR DESCRIPTION
**Pull request by aryan57**
I added the option for making a copy of files in a specified folder, which then can be automatically updated as a github repo if the user wants to (github part has to be done by user itself)

### CODE REVIEW

**Comment by agrawal-d** [comment]
Hi @aryan57,
Thanks for your PR. I'm not sure what it does. Can you explain what functionality you are trying to add, and what this PR does?

**Comment by aryan57** [comment]
I have seen many competitive coders having an archive of their codes in github. I wanted that too to be automated using this extension. 

Your code was very large and i don't know much about vs code extensions, so i just added my code at a place, where the copy of the file can be created whenever any test case is run.
(Now the archive folder can easily be automatically updated to the users github repo by a cron job. But this is not related to this extension)

I also added a functionality of adding the parsed time. Because i can judge my myself how much time i took solving a problem by looking at the time difference in parsed time and codeforces.com submission time.

You can close this PR as this isnt a good quality code.

But please add these two functionalities of adding the option to have the files prewritten with a parsed time and option to create a archive in a user-specified folder.

**Comment by agrawal-d** [comment]
Thanks for explaining. I will take a look at the weekend.

**Comment by agrawal-d** [comment]
Thanks for the PR. However, it does not work as expected and is not mergeable as such without a complete rewrite.

**Comment by aryan57** [comment]
No issues. But please bring these features in the coming versions.

**Pull request closed without merging**
