### PR TITLE
Add ability to cache compilations.

### PR DESCRIPTION
**Pull request by agrawal-d**
Co-authored-by: Mitko Nikov <mitkonikov01@gmail.com>

### CODE REVIEW

**Comment by mitkonikov** [comment]
Excellent job, I love it! I tested it out and it seems to be working well. I will now close the other pull request.
Do you think maybe it will be good also adding some icon when there is a cached version (something like the codicon-package), but this will require updating the UI with a message everytime the cachedVersion and editorVersion changes... :/ yea, it's kind of a missery to sync the UI. Do you have requests maybe about the docs or some tests?

### Thank you for all the wonderful work!

Can't wait to download it officially! 😄

**Comment by agrawal-d** [comment]
@mitkonikov this is actually not complete yet! There is a bug when the extension saves the file upon clicking run all, two compilations happen simultaneously, leading to ETXTBSY. I'm trying to fix it. If you come up with a solution please let me know.

**Comment by mitkonikov** [comment]
Is it the problem that the `compileFile` (Line 36) is executed inside the `runTestCases` function or?
Can you get me more details, so I can search for what is happening?

image

**Comment by agrawal-d** [comment]
The problem is  not so simple to be caused by a single line. Play around with the extension, and try running code from various places when the editor is dirty, there will be some inconsistencies. I'm trying to fix this, maybe you can get some ideas too.

**Pull request closed without merging**
