### PR TITLE
Built in kattis submission support

### PR DESCRIPTION
**Pull request by arnav-ag**
Placing the kattis submission client and configuration files from https://open.kattis.com/help/submit in ~/.kattis will allow you to automatically submit the written code and open the submission page in a new tab.

### CODE REVIEW

**Comment by agrawal-d** [comment]
Hey! Thanks for the PR! I'll review it as soon as I'm free ( Probably on Sunday ). I'm not aware of the Kattis platform, have you confirmed that this works properly?

In the meantime, can you fix the CI failure?

**Comment by arnav-ag** [comment]
Hey sorry, am new to GitHub so wasn't exactly sure on how to go around pushing my new commits into this request. What I have done for Kattis problems is:
- Change the filenames to be [KattisProblemID].extn (for example reversebinary.cpp for https://open.kattis.com/problems/reversebinary)
- Add a submit to Kattis option(like the already existing CodeForces autosubmission)
- This uses [Kattis Submission Client](https://open.kattis.com/help/submit); the files need to be placed in ~/.kattis

Have tested this on various problems and it seems to be working properly.

**Comment by agrawal-d** [comment]
Did you also test this on Windows?

**Comment by arnav-ag** [comment]
It's still untested on Windows as I'm working on MacOS.

**Comment by arnav-ag** [comment]
It is currently not working on Windows as the [Kattis submission client](https://github.com/Kattis/kattis-cli) isn't working either. Have submitted a PR there to rectify this issue.

**Comment by arnav-ag** [comment]
It's now working on Windows, but needs to use an [ammended submit client](https://github.com/Kattis/kattis-cli/pull/31) instead of the original as `os.getenv('HOME')` in the original script does not work on Windows.

**Comment by arnav-ag** [comment]
The PR on the Kattis Client repo has been accepted and merged, so this should work as expected now, using [the updated client](https://github.com/Kattis/kattis-cli)

**Comment by agrawal-d** [comment]
Hi @arnav-ag! I apologize for not looking at this PR for so long. If you want to still continue work on this, can you please rebase to the latest master to fix the conflicts? Thanks!

**Comment by agrawal-d** [comment]
@arnav-ag there are still some conflicts.

**Comment by arnav-ag** [comment]
How can I see these conflicts?

**Comment by arnav-ag** [comment]
Does that fix the issues? If not, could you point me towards the conflicts?

**Comment by agrawal-d** [comment]
@arnav-ag Looks great! I'll make some minor tweaks and then merge it! Thanks a lot!

**Comment by arnav-ag** [comment]
Do you want me to resolve the remaining conflict as well?

**Comment by arnav-ag** [comment]
I'm not too sure why the conflict is as is now, because it seems fine to me. Please have a look help to comment on any changes I need to make! Thanks!

**Comment by agrawal-d** [comment]
Thanks @arnav-ag! I've merged the changes, after fixing the conflicts. I really appreciate the work you did for this PR - thanks!
I have some small advice for you for your next contributions: Do not make so many extra commits. Instead, each commit should only contain one logical unit of change. Most of your commits were unnecessary, like "Fix this", "Fix that". Instead of creating a new commit, you should `amend` the previous commit.

You can take a look at this excellent git commit guide : https://zulip.readthedocs.io/en/latest/contributing/version-control.html#commit-discipline

Thanks again!

**Comment by arnav-ag** [comment]
Thanks so much for the guide! I wasn’t aware of this function and was wondering how other PRs had so few commits 😅

**Comment by agrawal-d** [comment]
@arnav-ag can you please test manually on the current master if Kattis is working properly and other functionality is not broken ( like Codeforces submit etc.)

If all is fine, I will push an update to VS Studio Marketplace.

**Comment by arnav-ag** [comment]
I've had to make some changes because there were issues in companion.ts where a function was expecting type problem but it was still being given type string as per before some previous commits. Should I submit a new PR? Also will update the docs as requested.

**Comment by agrawal-d** [comment]
Yeah, please make a new PR.

Divyanshu Agrawal

________________________________

**Pull request closed without merging**
